---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: inventory-ms
spec:
 selector:
   matchLabels:
     app: inventory-ms
 replicas: 2
 template:
   metadata:
     labels:
       app: inventory-ms
   spec:
     containers:
       - name: inventory-ms
         image: inventory-ms:latest
         imagePullPolicy: Never
         ports:
           - containerPort: 8081


---


apiVersion: v1
kind: Service
metadata:
 name: inventory-svc
spec:
 selector:
   app: inventory-ms
 ports:
   - protocol: "TCP"
     port: 8081
     targetPort: 8081
 type: NodePort


